version: '3.7'

networks:
  default:
    driver: bridge

services:
  node: 
    image: registry.handh.ru/redmine-hooks/node-app:latest
    networks: 
      - default
    ports:
      - "8001:8001"
    init: true
    restart: always

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: hooks
    networks: 
      - default