version: '3.7'

networks:
  default:
    driver: bridge

services:
  node: 
    build:
      context: ./
      dockerfile: Dockerfile
    networks: 
      - default
    ports:
      - "8001:8001"
    init: true
    restart: always

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: hooks
    networks: 
      - default

      