version: '3.7'

networks:
  default:
    driver: bridge

services:
  node: 
    build:
      context: ./
      dockerfile: Dockerfile
    networks: 
      - default
    ports:
      - "8001:8001"
    environment:
      - KEY_GITHUB
      - KEY_REDMINE
      - ADMIN_NAME=admin
      - ADMIN_PASS=password
    init: true     
    restart: always
    volumes:
      - "./app:/app" 

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hooks
    networks: 
      - default
